/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';
// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as ContactImport } from './routes/contact';
import { Route as IndexImport } from './routes/index';
import { Route as PrivacyPolicyImport } from './routes/privacy-policy';
import { Route as ResumeImport } from './routes/resume';
import { Route as ResumeAboutImport } from './routes/resume.about';
import { Route as ResumeEducationImport } from './routes/resume.education';
import { Route as ResumeExperienceImport } from './routes/resume.experience';
import { Route as ResumeExperienceIdImport } from './routes/resume.experience.$id';
import { Route as ResumeIndexImport } from './routes/resume.index';
import { Route as ResumeSkillsImport } from './routes/resume.skills';
import { Route as TermsOfServiceImport } from './routes/terms-of-service';
import { Route as WorkImport } from './routes/work';

// Create Virtual Routes

const ResumeExperienceIndexLazyImport = createFileRoute(
  '/resume/experience/'
)();

// Create/Update Routes

const WorkRoute = WorkImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRoute,
} as any);

const TermsOfServiceRoute = TermsOfServiceImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRoute,
} as any);

const ResumeRoute = ResumeImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any);

const PrivacyPolicyRoute = PrivacyPolicyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any);

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const ResumeIndexRoute = ResumeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeRoute,
} as any);

const ResumeSkillsRoute = ResumeSkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ResumeRoute,
} as any);

const ResumeExperienceRoute = ResumeExperienceImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => ResumeRoute,
} as any);

const ResumeEducationRoute = ResumeEducationImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => ResumeRoute,
} as any);

const ResumeAboutRoute = ResumeAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ResumeRoute,
} as any);

const ResumeExperienceIndexLazyRoute = ResumeExperienceIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeExperienceRoute,
} as any).lazy(() =>
  import('./routes/resume.experience.index.lazy').then((d) => d.Route)
);

const ResumeExperienceIdRoute = ResumeExperienceIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResumeExperienceRoute,
} as any).lazy(() =>
  import('./routes/resume.experience.$id.lazy').then((d) => d.Route)
);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/contact': {
      id: '/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof ContactImport;
      parentRoute: typeof rootRoute;
    };
    '/privacy-policy': {
      id: '/privacy-policy';
      path: '/privacy-policy';
      fullPath: '/privacy-policy';
      preLoaderRoute: typeof PrivacyPolicyImport;
      parentRoute: typeof rootRoute;
    };
    '/resume': {
      id: '/resume';
      path: '/resume';
      fullPath: '/resume';
      preLoaderRoute: typeof ResumeImport;
      parentRoute: typeof rootRoute;
    };
    '/terms-of-service': {
      id: '/terms-of-service';
      path: '/terms-of-service';
      fullPath: '/terms-of-service';
      preLoaderRoute: typeof TermsOfServiceImport;
      parentRoute: typeof rootRoute;
    };
    '/work': {
      id: '/work';
      path: '/work';
      fullPath: '/work';
      preLoaderRoute: typeof WorkImport;
      parentRoute: typeof rootRoute;
    };
    '/resume/about': {
      id: '/resume/about';
      path: '/about';
      fullPath: '/resume/about';
      preLoaderRoute: typeof ResumeAboutImport;
      parentRoute: typeof ResumeImport;
    };
    '/resume/education': {
      id: '/resume/education';
      path: '/education';
      fullPath: '/resume/education';
      preLoaderRoute: typeof ResumeEducationImport;
      parentRoute: typeof ResumeImport;
    };
    '/resume/experience': {
      id: '/resume/experience';
      path: '/experience';
      fullPath: '/resume/experience';
      preLoaderRoute: typeof ResumeExperienceImport;
      parentRoute: typeof ResumeImport;
    };
    '/resume/skills': {
      id: '/resume/skills';
      path: '/skills';
      fullPath: '/resume/skills';
      preLoaderRoute: typeof ResumeSkillsImport;
      parentRoute: typeof ResumeImport;
    };
    '/resume/': {
      id: '/resume/';
      path: '/';
      fullPath: '/resume/';
      preLoaderRoute: typeof ResumeIndexImport;
      parentRoute: typeof ResumeImport;
    };
    '/resume/experience/$id': {
      id: '/resume/experience/$id';
      path: '/$id';
      fullPath: '/resume/experience/$id';
      preLoaderRoute: typeof ResumeExperienceIdImport;
      parentRoute: typeof ResumeExperienceImport;
    };
    '/resume/experience/': {
      id: '/resume/experience/';
      path: '/';
      fullPath: '/resume/experience/';
      preLoaderRoute: typeof ResumeExperienceIndexLazyImport;
      parentRoute: typeof ResumeExperienceImport;
    };
  }
}

// Create and export the route tree

interface ResumeExperienceRouteChildren {
  ResumeExperienceIdRoute: typeof ResumeExperienceIdRoute;
  ResumeExperienceIndexLazyRoute: typeof ResumeExperienceIndexLazyRoute;
}

const ResumeExperienceRouteChildren: ResumeExperienceRouteChildren = {
  ResumeExperienceIdRoute: ResumeExperienceIdRoute,
  ResumeExperienceIndexLazyRoute: ResumeExperienceIndexLazyRoute,
};

const ResumeExperienceRouteWithChildren =
  ResumeExperienceRoute._addFileChildren(ResumeExperienceRouteChildren);

interface ResumeRouteChildren {
  ResumeAboutRoute: typeof ResumeAboutRoute;
  ResumeEducationRoute: typeof ResumeEducationRoute;
  ResumeExperienceRoute: typeof ResumeExperienceRouteWithChildren;
  ResumeSkillsRoute: typeof ResumeSkillsRoute;
  ResumeIndexRoute: typeof ResumeIndexRoute;
}

const ResumeRouteChildren: ResumeRouteChildren = {
  ResumeAboutRoute: ResumeAboutRoute,
  ResumeEducationRoute: ResumeEducationRoute,
  ResumeExperienceRoute: ResumeExperienceRouteWithChildren,
  ResumeSkillsRoute: ResumeSkillsRoute,
  ResumeIndexRoute: ResumeIndexRoute,
};

const ResumeRouteWithChildren =
  ResumeRoute._addFileChildren(ResumeRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/contact': typeof ContactRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/resume': typeof ResumeRouteWithChildren;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/work': typeof WorkRoute;
  '/resume/about': typeof ResumeAboutRoute;
  '/resume/education': typeof ResumeEducationRoute;
  '/resume/experience': typeof ResumeExperienceRouteWithChildren;
  '/resume/skills': typeof ResumeSkillsRoute;
  '/resume/': typeof ResumeIndexRoute;
  '/resume/experience/$id': typeof ResumeExperienceIdRoute;
  '/resume/experience/': typeof ResumeExperienceIndexLazyRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/contact': typeof ContactRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/work': typeof WorkRoute;
  '/resume/about': typeof ResumeAboutRoute;
  '/resume/education': typeof ResumeEducationRoute;
  '/resume/skills': typeof ResumeSkillsRoute;
  '/resume': typeof ResumeIndexRoute;
  '/resume/experience/$id': typeof ResumeExperienceIdRoute;
  '/resume/experience': typeof ResumeExperienceIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/contact': typeof ContactRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/resume': typeof ResumeRouteWithChildren;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/work': typeof WorkRoute;
  '/resume/about': typeof ResumeAboutRoute;
  '/resume/education': typeof ResumeEducationRoute;
  '/resume/experience': typeof ResumeExperienceRouteWithChildren;
  '/resume/skills': typeof ResumeSkillsRoute;
  '/resume/': typeof ResumeIndexRoute;
  '/resume/experience/$id': typeof ResumeExperienceIdRoute;
  '/resume/experience/': typeof ResumeExperienceIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy-policy'
    | '/resume'
    | '/terms-of-service'
    | '/work'
    | '/resume/about'
    | '/resume/education'
    | '/resume/experience'
    | '/resume/skills'
    | '/resume/'
    | '/resume/experience/$id'
    | '/resume/experience/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/contact'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/work'
    | '/resume/about'
    | '/resume/education'
    | '/resume/skills'
    | '/resume'
    | '/resume/experience/$id'
    | '/resume/experience';
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy-policy'
    | '/resume'
    | '/terms-of-service'
    | '/work'
    | '/resume/about'
    | '/resume/education'
    | '/resume/experience'
    | '/resume/skills'
    | '/resume/'
    | '/resume/experience/$id'
    | '/resume/experience/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ContactRoute: typeof ContactRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  ResumeRoute: typeof ResumeRouteWithChildren;
  TermsOfServiceRoute: typeof TermsOfServiceRoute;
  WorkRoute: typeof WorkRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResumeRoute: ResumeRouteWithChildren,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WorkRoute: WorkRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact",
        "/privacy-policy",
        "/resume",
        "/terms-of-service",
        "/work"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.tsx"
    },
    "/resume": {
      "filePath": "resume.tsx",
      "children": [
        "/resume/about",
        "/resume/education",
        "/resume/experience",
        "/resume/skills",
        "/resume/"
      ]
    },
    "/terms-of-service": {
      "filePath": "terms-of-service.tsx"
    },
    "/work": {
      "filePath": "work.tsx"
    },
    "/resume/about": {
      "filePath": "resume.about.tsx",
      "parent": "/resume"
    },
    "/resume/education": {
      "filePath": "resume.education.tsx",
      "parent": "/resume"
    },
    "/resume/experience": {
      "filePath": "resume.experience.tsx",
      "parent": "/resume",
      "children": [
        "/resume/experience/$id",
        "/resume/experience/"
      ]
    },
    "/resume/skills": {
      "filePath": "resume.skills.tsx",
      "parent": "/resume"
    },
    "/resume/": {
      "filePath": "resume.index.tsx",
      "parent": "/resume"
    },
    "/resume/experience/$id": {
      "filePath": "resume.experience.$id.tsx",
      "parent": "/resume/experience"
    },
    "/resume/experience/": {
      "filePath": "resume.experience.index.lazy.tsx",
      "parent": "/resume/experience"
    }
  }
}
ROUTE_MANIFEST_END */
