import type { FilterKey } from '@/types/filters.types';

export const filterConfig = {
  technology: {
    label: 'Technology',
    multiple: true,
    options: [
      'AWS',
      'Angular',
      'BootStrap',
      'CSS3',
      'Docker',
      'Express.js',
      'Figma',
      'Framer Motion',
      'GitHub',
      'GitLab',
      'Gulp',
      'HTML5',
      'Hotjar',
      'JavaScript',
      'Material UI',
      'MySQL',
      'Node.js',
      'PHP',
      'PNPM',
      'Playwright',
      'Radix UI',
      'React',
      'React Native',
      'React Query',
      'SCSS',
      'Sentry',
      'ShadeCn',
      'Storybook',
      'TailwindCSS',
      'TanStack Form',
      'TanStack Router',
      'TypeScript',
      'Vite',
      'Vitest',
      'WCAG',
      'Zustand',
      'jQuery',
    ],
  },
  location: {
    label: 'Location',
    multiple: false,
    options: ['London', 'Remote', 'Turin', 'Vienna'],
  },
  company: {
    label: 'Company',
    multiple: false,
    options: [
      'Eis World',
      'Hydrogrid',
      'Loro Piana',
      'VideoSmart',
      'World Data Lab',
    ],
  },
};

export const categoryColorClasses: Record<FilterKey, string> = {
  technology: 'bg-work text-background',
  location: 'bg-contact text-background',
  company: 'bg-resume text-background',
};
