import type { FilterKey } from '@/types/filters.types';

export const filterConfig = {
  company: {
    label: 'Company',
    multiple: false,
    options: [
      'Eis World',
      'Hydrogrid',
      'Loro Piana',
      'VideoSmart',
      'World Data Lab',
    ],
  },
  location: {
    label: 'Location',
    multiple: false,
    options: ['London', 'Remote', 'Turin', 'Vienna'],
  },
  role: {
    label: 'Role',
    multiple: false,
    options: ['Front End Developer', 'Full Stack Developer'],
  },
  technology: {
    label: 'Technology',
    multiple: true,
    options: [
      'AWS',
      'AWS S3',
      'Angular',
      'BootStrap',
      'CSS3',
      'Docker',
      'Docker Compose',
      'Express.js',
      'Figma',
      'Framer Motion',
      'GitHub',
      'GitLab',
      'Gulp',
      'HTML5',
      'Hotjar',
      'JavaScript',
      'Material UI',
      'MySQL',
      'Neon',
      'Node.js',
      'PHP',
      'PNPM',
      'PostgreSQL',
      'Playwright',
      'Prisma',
      'Radix UI',
      'React',
      'React Native',
      'React Query',
      'SCSS',
      'Sentry',
      'ShadeCn',
      'SvelteKit',
      'Storybook',
      'TailwindCSS',
      'TanStack Form',
      'TanStack Query',
      'TanStack Router',
      'TypeScript',
      'Vercel',
      'Vite',
      'Vitest',
      'WCAG',
      'Zustand',
      'jQuery',
    ],
  },
};

export const categoryColorClasses: Record<FilterKey, string> = {
  technology: 'bg-work text-background',
  location: 'bg-contact text-background',
  company: 'bg-resume text-background',
  role: 'bg-gray',
};
