import type { FilterKey } from '@/types/filters.types';

export const filterConfig = {
  company: {
    label: 'Company',
    multiple: false,
    options: [
      'Eis World',
      'Hydrogrid',
      'Loro Piana',
      'VideoSmart',
      'World Data Lab',
    ],
  },
  location: {
    label: 'Location',
    multiple: false,
    options: ['London', 'Remote', 'Turin', 'Vienna'],
  },
  role: {
    label: 'Role',
    multiple: false,
    options: ['Front End Developer', 'Full Stack Developer'],
  },
  technology: {
    label: 'Technology',
    multiple: true,
    options: [
      'AWS',
      'AWS S3',
      'Alchemy API',
      'Angular',
      'BootStrap',
      'CSS3',
      'Docker',
      'Docker Compose',
      'Express.js',
      'Expo',
      'FastAPI',
      'Figma',
      'Framer Motion',
      'GitHub',
      'GitLab',
      'Gulp',
      'Hardhat',
      'HTML5',
      'Hotjar',
      'JavaScript',
      'JWT',
      'Lottie',
      'Material UI',
      'MongoDB',
      'Mongoose',
      'MySQL',
      'NativeWind',
      'Neon',
      'Next.js',
      'Node.js',
      'OpenAI API',
      'PHP',
      'PNPM',
      'Pinata IPFS',
      'Playwright',
      'PostgreSQL',
      'Prisma',
      'Pydantic',
      'Python',
      'Radix UI',
      'React',
      'React Native',
      'React Query',
      'Render',
      'SCSS',
      'Sentry',
      'ShadeCn',
      'Solidity',
      'SQLModel',
      'SvelteKit',
      'Storybook',
      'TailwindCSS',
      'TanStack Form',
      'TanStack Query',
      'TanStack Router',
      'TypeScript',
      'Vercel',
      'Vite',
      'Vitest',
      'WCAG',
      'Zustand',
      'bcrypt',
      'jQuery',
    ],
  },
};

export const categoryColorClasses: Record<FilterKey, string> = {
  technology: 'bg-work text-background',
  location: 'bg-contact text-background',
  company: 'bg-resume text-background',
  role: 'bg-gray',
};
