import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const adminEmails = [
  'matteo.soresini@hotmail.it',
  'matteo.soresini90@gmail.com',
];
const virtualAdminId = 'admin_virtual_id';

async function main() {
  await prisma.$transaction([
    prisma.projectExperience.deleteMany(),
    prisma.project.deleteMany(),
    prisma.experience.deleteMany(),
  ]);

  await prisma.user.upsert({
    where: { id: virtualAdminId },
    update: {},
    create: {
      id: virtualAdminId,
      email: 'matteo@admin.com',
      name: 'Matteo',
      avatarUrl: 'https://matteosoresini.com/favicon.png',
      role: 'admin',
    },
  });

  await Promise.all(
    adminEmails.map((email) =>
      prisma.user.upsert({
        where: { email },
        update: {},
        create: {
          email,
          name: 'Matteo',
          avatarUrl: 'https://matteosoresini.com/favicon.png',
          role: 'admin',
        },
      })
    )
  );

  await prisma.experience.create({
    data: {
      company: 'World Data Lab',
      title: 'Front End Developer',
      role: 'Front End Developer',
      slug: 'world-data-lab',
      location: 'Vienna, AT',
      url: 'https://worlddatalab.com/',
      isRemote: true,
      startDate: new Date('2022-03-01'),
      endDate: new Date('2025-07-01'),
      description:
        'Built responsive web applications delivering real-time data and projections out to 2030. Developed models for data visualization on various global issues such as population, hunger, poverty, and water shortage.',
      duties: [
        'Built interactive, UIs using React, TypeScript, TailwindCSS, and Zustand',
        'Integrated routing, forms, and queries via TanStack tools',
        'Developed a lightweight Node.js API with Express',
        'Implemented testing with Vitest and Playwright, monitored UX with Sentry and Hotjar',
        'Collaborated in CI/CD setup using Docker, GitHub Actions, and AWS',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Angular',
        'JavaScript',
        'Node.js',
        'Express.js',
        'AWS',
        'Docker',
        'Zustand',
        'TailwindCSS',
        'TanStack Router',
        'TanStack Form',
        'TanStack Query',
        'Framer Motion',
        'ShadeCn',
        'Material UI',
        'Radix UI',
        'Vite',
        'PNPM',
        'Vitest',
        'Playwright',
        'Storybook',
        'GitHub',
        'Atlassian Suite (Jira, Confluence)',
        'Sentry',
        'Hotjar',
        'Figma',
      ],
      imageUrl: null,
      projects: {
        create: [
          {
            title: 'World Emissions Clock',
            url: 'https://worldemissions.io/',
          },
          {
            title: 'Internet Poverty Index',
            url: 'https://internetpoverty.io/',
          },
          { title: 'Africa Youth Clock', url: 'https://africayouthjobs.io/' },
          {
            title: 'Africa Social Protection',
            url: 'https://africasocialprotection.io/',
          },
          { title: 'Water Crisis Clock', url: 'https://worldwater.io/' },
        ],
      },
    },
  });

  await prisma.experience.createMany({
    data: [
      {
        company: 'Hydrogrid',
        title: 'Front End Developer',
        role: 'Front End Developer',
        slug: 'hydrogrid',
        location: 'Vienna, AT',
        url: 'https://hydrogrid.ai/',
        isRemote: false,
        startDate: new Date('2020-11-01'),
        endDate: new Date('2022-02-28'),
        description:
          'Maintained real-time electricity dashboards for Hydrogrid using React with Hooks. Supported both client-facing and internal systems.',
        duties: [
          'Developed and maintained real-time electricity dashboards using React, TypeScript, and TailwindCSS',
          'Built an internal platform with React Native for company staff to manage client information',
          'Implemented interactive UIs using React Hooks for responsive and high-performance experiences',
          'Contributed to system observability and UX improvements via Sentry, Hotjar, and Figma',
        ],
        technologies: [
          'React',
          'TypeScript',
          'React Native',
          'JavaScript',
          'TailwindCSS',
          'GitHub',
          'Atlassian Suite (Jira, Confluence)',
          'Sentry',
          'Hotjar',
          'Figma',
        ],
        imageUrl: null,
      },
      {
        company: 'Eis World',
        title: 'Front End Developer',
        role: 'Front End Developer',
        slug: 'eis-world',
        location: 'Turin, IT',
        url: 'https://orbyta.it/',
        isRemote: false,
        startDate: new Date('2019-01-01'),
        endDate: new Date('2020-01-01'),
        description:
          'Built websites from scratch, led GIT merging processes, and handled backend tasks using PHP and MySQL',
        duties: [
          'Developed websites using modern web technologies',
          'Managed Git merges as team lead',
          'Handled backend with PHP and MySQL, including PDF generation',
        ],
        technologies: [
          'JavaScript',
          'PHP',
          'MySQL',
          'SCSS',
          'TailwindCSS',
          'GitLab',
          'Atlassian Suite (Jira, Confluence)',
        ],
        imageUrl: null,
      },
      {
        company: 'Loro Piana',
        title: 'Front End Developer',
        role: 'Front End Developer',
        slug: 'loro-piana',
        location: 'Turin, IT',
        url: 'https://it.loropiana.com/it/',
        isRemote: false,
        startDate: new Date('2018-01-01'),
        endDate: new Date('2019-01-01'),
        description:
          'Built a new e-commerce platform focused on front-end design and WCAG compliance.',
        duties: [
          'Developed a custom e-commerce frontend',
          'Focused on UI/UX and WCAG accessibility standards',
        ],
        technologies: [
          'JavaScript',
          'jQuery',
          'WCAG',
          'BootStrap',
          'HTML5',
          'CSS3',
          'Gulp',
        ],
        imageUrl: null,
      },
      {
        company: 'VideoSmart',
        title: 'Front End Developer',
        role: 'Front End Developer',
        slug: 'videosmart',
        location: 'London, UK',
        url: 'https://videosmart.com/',
        isRemote: false,
        startDate: new Date('2017-04-01'),
        endDate: new Date('2018-01-01'),
        description:
          'Created responsive HTML5 landing pages and email templates. Ensured cross-browser compatibility and responsiveness across devices.',
        duties: [
          'Created responsive HTML5 landing pages and email templates based on specified designs',
          'Ensured cross-browser compatibility and responsiveness on various devices',
        ],
        technologies: ['JavaScript', 'jQuery', 'BootStrap', 'HTML5', 'CSS3'],
        imageUrl: null,
      },
    ],
  });

  await prisma.project.createMany({
    data: [
      {
        title: 'Mind Earth (Assignment)',
        number: '01',
        description:
          'A full-stack geospatial platform built with Next.js, FastAPI, PostgreSQL, and Docker. Mind Earth lets you explore geo-data, population stats, and manage authentication seamlessly.',
        slug: 'mind-earth',
        company: 'Mind Earth - Assignment',
        isRemote: true,
        technologies: [
          'Next.js 15',
          'TypeScript',
          'Zustand',
          'Axios',
          'TailwindCSS',
          'Python',
          'FastAPI',
          'SQLModel',
          'Pydantic',
          'PostgreSQL',
          'JWT',
          'bcrypt',
          'Docker',
          'Docker Compose',
        ],
        repoUrl: 'https://github.com/Matteobikk90/mind-earth',
        demoUrl: null,
        imageUrl: 'mind-earth.png',
        isFeatured: false,
        createdAt: new Date('2025-08-15'),
        updatedAt: new Date(),
        role: 'Full Stack Developer',
      },
      {
        title: 'File Upload',
        number: '02',
        description:
          'A simple file upload and management app built with SvelteKit, PostgreSQL, and Docker.',
        slug: 'file-upload',
        company: 'Assignment',
        isRemote: true,
        technologies: [
          'SvelteKit',
          'TypeScript',
          'PostgreSQL',
          'Prisma',
          'Docker',
          'Docker Compose',
          'AWS S3',
          'Neon',
          'Vercel',
        ],
        repoUrl: 'https://github.com/Matteobikk90/pack-file-upload',
        demoUrl: 'https://pack-file-upload-gray.vercel.app/',
        imageUrl: 'pack.png',
        isFeatured: false,
        createdAt: new Date('2025-08-01'),
        updatedAt: new Date(),
        role: 'Full Stack Developer',
      },
      {
        title: 'Full Stack Portfolio',
        number: '03',
        description: 'Personal full-stack portfolio project.',
        slug: 'full-stack-portfolio',
        technologies: [
          'React',
          'Zustand',
          'Node.js',
          'Express.js',
          'i18n',
          'TailwindCSS',
          'TypeScript',
          'Prisma',
          'PostgreSQL',
          'zod',
          'OpenAI',
          'Socket.io',
          'AWS',
          'Docker',
          'Sentry',
          'Vite',
          'PNPM',
          'MSW',
          'Storybook',
          'Vitest',
          'Playwright',
        ],
        repoUrl: 'https://github.com/Matteobikk90/full-stack-portfolio',
        company: 'Remote',
        isRemote: true,
        demoUrl: 'https://matteosoresini.com/',
        imageUrl: null,
        isFeatured: true,
        createdAt: new Date('2025-05-01'),
        updatedAt: new Date(),
        role: 'Full Stack Developer',
      },
      {
        title: 'Africa Youth Clock (at World Data Lab)',
        number: '04',
        description: 'Data visualization of youth demographics in Africa.',
        slug: 'africa-youth-clock',
        company: 'World Data Lab',
        isRemote: true,
        technologies: [
          'React',
          'TypeScript',
          'React Router',
          'React Query',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://africayouthjobs.io/',
        imageUrl: 'youth.png',
        isFeatured: false,
        createdAt: new Date('2024-07-01'),
        updatedAt: new Date(),
        role: 'Front End Developer',
      },
      {
        title: 'Africa Social Protection (at World Data Lab)',
        number: '05',
        description: 'Map of social protection initiatives in Africa.',
        slug: 'africa-social-protection',
        company: 'World Data Lab',
        isRemote: true,
        technologies: [
          'React',
          'TypeScript',
          'React Query',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://africasocialprotection.io/',
        imageUrl: 'social.png',
        isFeatured: false,
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date(),
        role: 'Front End Developer',
      },
      {
        title: 'Water Crisis Clock (at World Data Lab)',
        number: '06',
        description: 'Visualization of global water stress.',
        slug: 'water-crisis-clock',
        company: 'World Data Lab',
        isRemote: true,
        technologies: [
          'React',
          'TypeScript',
          'GraphQL',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://worldwater.io/',
        imageUrl: 'water.png',
        isFeatured: false,
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date(),
        role: 'Front End Developer',
      },
      {
        title: 'Internet Poverty Index (at World Data Lab)',
        number: '07',
        description: 'Interactive data on digital access inequality.',
        slug: 'internet-poverty-index',
        company: 'World Data Lab',
        isRemote: true,
        technologies: [
          'React',
          'ES6',
          'GraphQL',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://internetpoverty.io/',
        imageUrl: 'internet.png',
        isFeatured: false,
        createdAt: new Date('2022-06-01'),
        updatedAt: new Date(),
        role: 'Front End Developer',
      },
      {
        title: 'World Emissions Clock (at World Data Lab)',
        number: '08',
        description: 'Global CO₂ emissions visualized over time.',
        slug: 'world-emissions-clock',
        company: 'World Data Lab',
        isRemote: true,
        technologies: ['React', 'ES6', 'TailwindCSS', 'Leaflet', 'pako'],
        repoUrl: null,
        demoUrl: 'https://worldemissions.io/',
        imageUrl: 'emissions.png',
        isFeatured: false,
        createdAt: new Date('2022-03-01'),
        updatedAt: new Date(),
        role: 'Front End Developer',
      },
      {
        title: 'Blendon Barber Shop',
        number: '09',
        description: 'Business website for a local barbershop.',
        slug: 'blendon-barber-shop',
        company: 'Remote',
        isRemote: true,
        technologies: [
          'React',
          'Node.js',
          'Vercel',
          'Firebase',
          'TailwindCSS',
          'TypeScript',
        ],
        repoUrl: 'https://github.com/Matteobikk90/barber-shop',
        demoUrl: 'https://blendon-barber-shop.it/',
        imageUrl: null,
        isFeatured: false,
        createdAt: new Date('2022-01-01'),
        updatedAt: new Date(),
        role: 'Full Stack Developer',
      },
      {
        title: 'AGS Sorit Illuminazione',
        number: '10',
        description: 'Corporate website for lighting company.',
        slug: 'ags-illuminazione',
        company: 'Remote',
        isRemote: true,
        technologies: ['HTML5', 'CSS3', 'JavaScript', 'Node.js', 'Firebase'],
        repoUrl: null,
        demoUrl: 'https://agsoritilluminazione.com/',
        imageUrl: null,
        isFeatured: false,
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date(),
        role: 'Full Stack Developer',
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error('Error seeding:', e);
  })
  .finally(() => {
    prisma.$disconnect();
  });
