import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const adminEmails = [
  'matteo.soresini@hotmail.it',
  'matteo.soresini90@gmail.com',
];

async function main() {
  await prisma.$transaction([
    prisma.projectExperience.deleteMany(),
    prisma.project.deleteMany(),
    prisma.experience.deleteMany(),
  ]);

  await Promise.all(
    adminEmails.map((email) =>
      prisma.user.upsert({
        where: { email },
        update: {},
        create: {
          email,
          name: 'Matteo',
          avatarUrl: 'https://matteosoresini.com/favicon.png',
          role: 'admin',
        },
      })
    )
  );

  await prisma.experience.create({
    data: {
      company: 'World Data Lab',
      title: 'Front End Developer',
      slug: 'world-data-lab',
      location: 'Vienna, AT',
      url: 'https://worlddatalab.com/',
      isRemote: true,
      startDate: new Date('2022-03-01'),
      endDate: new Date('2025-07-01'),
      description:
        'Built responsive web applications delivering real-time data and projections out to 2030. Developed models for data visualization on various global issues such as population, hunger, poverty, and water shortage.',
      duties: [
        'Built responsive web applications delivering real-time data and projections out to 2030',
        'Developed models for data visualization on global issues',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Angular',
        'JavaScaript',
        'Node.js',
        'Express.js',
        'Prisma',
        'PostgreSQL',
        'Zustand',
        'TailwindCSS',
        'TanStack Router',
        'TanStack Form',
        'React Query',
        'Framer Motion',
        'ShadeCn',
        'Material UI',
        'Radix UI',
        'Vite',
        'PNPM',
        'Vitest',
        'Playwright',
        'Storybook',
        'GitHub',
        'GitLab',
        'Atlassian Suite (Jira, Confluence)',
        'Sentry',
        'Hotjar',
        'Figma',
      ],
      imageUrl: null,
      projects: {
        create: [
          {
            title: 'World Emissions Clock',
            url: 'https://worldemissions.io/',
          },
          {
            title: 'Internet Poverty Index',
            url: 'https://internetpoverty.io/',
          },
          { title: 'Africa Youth Clock', url: 'https://africayouthjobs.io/' },
          {
            title: 'Africa Social Protection',
            url: 'https://africasocialprotection.io/',
          },
          { title: 'Water Crisis Clock', url: 'https://worldwater.io/' },
          {
            title: 'Categories Clock',
            url: 'https://futureconsumerdemand.io/',
          },
        ],
      },
    },
  });

  await prisma.experience.createMany({
    data: [
      {
        company: 'Hydrogrid',
        title: 'Front End Developer',
        slug: 'hydrogrid',
        location: 'Vienna, AT',
        url: 'https://hydrogrid.ai/',
        isRemote: false,
        startDate: new Date('2020-11-01'),
        endDate: new Date('2022-02-28'),
        description:
          'Maintained real-time electricity dashboards for Hydrogrid using React with Hooks. Supported both client-facing and internal systems.',
        duties: [
          'Designed and maintained real-time electricity dashboards',
          'Used React.js with Hooks for fast, secure, and interactive UIs',
          'Developed internal dashboard for simulation and onboarding',
        ],
        technologies: [
          'React',
          'TypeScript',
          'React Native',
          'JavaScaript',
          'TailwindCSS',
          'GitHub',
          'GitLab',
          'Atlassian Suite (Jira, Confluence)',
          'Sentry',
          'Hotjar',
          'Figma',
        ],
        imageUrl: null,
      },
      {
        company: 'Eis World',
        title: 'Front End Developer',
        slug: 'eis-world',
        location: 'Turin, IT',
        url: 'https://orbyta.it/',
        isRemote: false,
        startDate: new Date('2019-01-01'),
        endDate: new Date('2020-01-01'),
        description:
          'Built websites from scratch, led GIT merging processes, and handled backend tasks using PHP and MySQL.',
        duties: [
          'Developed websites using modern web technologies',
          'Managed Git merges as team lead',
          'Handled backend with PHP and MySQL, including PDF generation',
        ],
        technologies: [
          'JavaScript',
          'PHP',
          'MySQL',
          'SCSS',
          'TailwindCSS',
          'GitLab',
          'Atlassian Suite (Jira, Confluence)',
        ],
        imageUrl: null,
      },
      {
        company: 'Loro Piana',
        title: 'Front End Developer',
        slug: 'loro-piana',
        location: 'Turin, IT',
        url: 'https://it.loropiana.com/it/',
        isRemote: false,
        startDate: new Date('2018-01-01'),
        endDate: new Date('2019-01-01'),
        description:
          'Built a new e-commerce platform focused on front-end design and WCAG compliance.',
        duties: [
          'Developed a custom e-commerce frontend',
          'Focused on UI/UX and WCAG accessibility standards',
        ],
        technologies: [
          'JavaScript',
          'jQuery',
          'WCAG',
          'BootStrap',
          'HTML5',
          'CSS3',
          'Gulp',
        ],
        imageUrl: null,
      },
      {
        company: 'VideoSmart',
        title: 'Front End Developer',
        slug: 'videosmart',
        location: 'London, UK',
        url: 'https://www.videosmart.com/',
        isRemote: false,
        startDate: new Date('2017-04-01'),
        endDate: new Date('2018-01-01'),
        description:
          'Created responsive HTML5 landing pages and email templates. Ensured cross-browser compatibility and responsiveness across devices.',
        duties: [
          'Created responsive HTML5 landing pages and email templates based on specified designs',
          'Ensured cross-browser compatibility and responsiveness on various devices',
        ],
        technologies: ['JavaScript', 'jQuery', 'BootStrap', 'HTML5', 'CSS3'],
        imageUrl: null,
      },
    ],
  });

  await prisma.project.createMany({
    data: [
      {
        title: 'Full Stack Portfolio',
        number: '01',
        description: 'Personal full-stack portfolio project.',
        slug: 'full-stack-portfolio',
        technologies: [
          'React',
          'Zustand',
          'Node.js',
          'Express.js',
          'i18n',
          'TailwindCSS',
          'TypeScript',
          'Prisma',
          'PostgreSQL',
          'AWS',
          'Docker',
          'Sentry',
          'Vite',
          'PNPM',
        ],
        repoUrl: 'https://github.com/Matteobikk90/full-stack-portfolio',
        demoUrl: 'https://matteosoresini.com/',
        imageUrl: null,
        isFeatured: true,
        createdAt: new Date('2025-05-01'),
        updatedAt: new Date(),
      },
      {
        title: 'Africa Youth Clock (at World Data Lab)',
        number: '02',
        description: 'Data visualization of youth demographics in Africa.',
        slug: 'africa-youth-clock',
        technologies: [
          'React',
          'TypeScript',
          'React Router',
          'React Query',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://africayouthjobs.io/',
        imageUrl: 'youth.png',
        isFeatured: false,
        createdAt: new Date('2024-07-01'),
        updatedAt: new Date(),
      },
      {
        title: 'Categories Clock (at World Data Lab)',
        number: '03',
        description: 'Forecast of future consumer demand trends.',
        slug: 'categories-clock',
        technologies: [
          'React',
          'TypeScript',
          'React Router',
          'React Query',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://futureconsumerdemand.io/',
        imageUrl: 'categories.png',
        isFeatured: false,
        createdAt: new Date('2024-03-01'),
        updatedAt: new Date(),
      },
      {
        title: 'Africa Social Protection (at World Data Lab)',
        number: '04',
        description: 'Map of social protection initiatives in Africa.',
        slug: 'africa-social-protection',
        technologies: [
          'React',
          'TypeScript',
          'React Query',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://africasocialprotection.io/',
        imageUrl: 'social.png',
        isFeatured: false,
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date(),
      },
      {
        title: 'Water Crisis Clock (at World Data Lab)',
        number: '05',
        description: 'Visualization of global water stress.',
        slug: 'water-crisis-clock',
        technologies: [
          'React',
          'TypeScript',
          'GraphQL',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://worldwater.io/',
        imageUrl: 'water.png',
        isFeatured: false,
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date(),
      },
      {
        title: 'Internet Poverty Index (at World Data Lab)',
        number: '06',
        description: 'Interactive data on digital access inequality.',
        slug: 'internet-poverty-index',
        technologies: [
          'React',
          'ES6',
          'GraphQL',
          'i18next',
          'TailwindCSS',
          'Leaflet',
        ],
        repoUrl: null,
        demoUrl: 'https://internetpoverty.io/',
        imageUrl: 'internet.png',
        isFeatured: false,
        createdAt: new Date('2022-06-01'),
        updatedAt: new Date(),
      },
      {
        title: 'World Emissions Clock (at World Data Lab)',
        number: '07',
        description: 'Global CO₂ emissions visualized over time.',
        slug: 'world-emissions-clock',
        technologies: ['React', 'ES6', 'TailwindCSS', 'Leaflet', 'pako'],
        repoUrl: null,
        demoUrl: 'https://worldemissions.io/',
        imageUrl: 'emissions.png',
        isFeatured: false,
        createdAt: new Date('2022-03-01'),
        updatedAt: new Date(),
      },
      {
        title: 'Blendon Barber Shop',
        number: '08',
        description: 'Business website for a local barbershop.',
        slug: 'blendon-barber-shop',
        technologies: [
          'React',
          'Node.js',
          'Vercel',
          'Firebase',
          'TailwindCSS',
          'TypeScript',
        ],
        repoUrl: 'https://github.com/Matteobikk90/barber-shop',
        demoUrl: 'https://blendon-barber-shop.it/',
        imageUrl: null,
        isFeatured: false,
        createdAt: new Date('2022-01-01'),
        updatedAt: new Date(),
      },
      {
        title: 'AGS Ori Illuminazione',
        number: '09',
        description: 'Corporate website for lighting company.',
        slug: 'ags-illuminazione',
        technologies: ['HTML5', 'CSS3', 'JavaScript'],
        repoUrl: null,
        demoUrl: 'https://agsoritilluminazione.com/',
        imageUrl: null,
        isFeatured: false,
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date(),
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error('Error seeding:', e);
  })
  .finally(() => {
    prisma.$disconnect();
  });
